function emt = setEmtFromSalt( ...
    emt,salt, ...
    sysSize_TD,tSamp_TD,deltaT_TD, ...
    x_v)

[idxGenrou_Idq,idxGenrou_Ifd,idxGenrou_Edq,idxGenrou_Efd,idxGenrou_Wr,idxGenrou_Theta, ...
    idxGenrou_IphABC,idxGenrou_Tm] = getGenrouIndices_SS;
[idxIbrGFM_IphABC,idxIbrGFM_Vg,idxIbrGFM_Vo,idxIbrGFM_If,idxIbrGFM_Io, ...
    idxIbrGFM_Vi,idxIbrGFM_Gamma,idxIbrGFM_IfRef,idxIbrGFM_X,idxIbrGFM_Wr, ...
    idxIbrGFM_VoRefDroop_q,idxIbrGFM_PqAvg,idxIbrGFM_Theta, ...
    idxIbrGFM_Vo_VR_avg,idxIbrGFM_Vo_VR,idxIbrGFM_VoRef] = getIbrGFMIndices_SS;
[idxLoadComp_Vs,idxLoadComp_IphABC,idxLoadComp_WSlip,idxLoadComp_ThetaSys, ...
    idxLoadComp_Is,idxLoadComp_Ir,idxLoadComp_Wr, ...
    idxLoadComp_PQ,idxLoadComp_Vm,idxLoadComp_Izip] = getLoadCompIndices_SS;

[idxGenrouTD_I,idxGenrouTD_E,idxGenrouTD_Efd,idxGenrouTD_Wr,idxGenrouTD_Theta,idxGenrouTD_Iabc, ...
    idxGenrouTD_Tm] = getGenrouIndicesTD;
[idxIbrGFMTD_Iabc,idxIbrGFMTD_Vg,idxIbrGFMTD_Vo,idxIbrGFMTD_If,idxIbrGFMTD_Io, ...
        idxIbrGFMTD_Vi,idxIbrGFMTD_Gamma,idxIbrGFMTD_IfRef,idxIbrGFMTD_X,idxIbrGFMTD_Wr, ...
        idxIbrGFMTD_VoRefDroop_q,idxIbrGFMTD_PqAvg,idxIbrGFMTD_Theta, ...
        idxIbrGFMTD_Vo_VR_avg,idxIbrGFMTD_Vo_VR,idxIbrGFMTD_VoRef] = ...
        getIbrGFMIndicesTD;
[idxLoadCompTD_Vs,idxLoadCompTD_Iabc,idxLoadCompTD_WSlip, ...
    idxLoadCompTD_ThetaSys,idxLoadCompTD_Is,idxLoadCompTD_Ir, ...
    idxLoadCompTD_Wr, ...
    idxLoadCompTD_PQ,idxLoadCompTD_VmPreFilt,idxLoadCompTD_Vm, ...
    idxLoadCompTD_Izip] = getLoadCompIndicesTD;

%%
% ---------------------------- STATE VARIABLES ----------------------------

% Initialize state variables
emt.x_v_prevTime = zeros(sysSize_TD,1);
emt.x_v = zeros(sysSize_TD,1);
% Initialize calculations of previous times for dynamic
t_negDelta_0 = [(tSamp_TD(end)-deltaT_TD);0];
% Initialize final frequency
idxW_SS = salt.getRowIdx_w;
w = salt.x_v(idxW_SS);
f = w/(2*pi);
f_DC = 0;

% ---> LINEAR X_V (AT BUSES)
% From freq domain sim
funGetIndices_Vabc = @(~)salt.getRowIdxAbc_fromBusNums(salt.bus);
Vabc_negDeltaT_0 = getTimeDomainSignal_iDFT(t_negDelta_0, ...
    funGetIndices_Vabc,x_v,f,1);
% To time domain init
idxLin_TD = emt.getRowIdxAbc_fromBusNums(emt.bus);
emt.x_v_prevTime(idxLin_TD) = Vabc_negDeltaT_0(:,1);
emt.x_v(idxLin_TD) = Vabc_negDeltaT_0(:,2);

% ---> DYNAMIC X_V (AT GEN, EXC, GOV)
% Generator
for idxGen = 1:salt.numGenrou
    % Get indicies
    idxGenrou_SS_DC = @(~)salt.getRowIdx_fromGenrouIndices(idxGen) + ...
        [idxGenrou_Idq,idxGenrou_Ifd,idxGenrou_Edq,idxGenrou_Efd,idxGenrou_Wr,idxGenrou_Theta, ...
        idxGenrou_Tm] ...
        -1;
    idxGenrou_SS_W = @(~)salt.getRowIdx_fromGenrouIndices(idxGen) + ...
        idxGenrou_IphABC ...
        -1;
    idxGenrou_TD = emt.getRowIdx_fromGenrouIndices(idxGen) + ...
        ... DC
        [idxGenrouTD_I([1 2 4]),idxGenrouTD_E([1 2]),idxGenrouTD_Efd,idxGenrouTD_Wr, ...
        idxGenrouTD_Theta,idxGenrouTD_Tm, ...
        ... W
        idxGenrouTD_Iabc] ...
        -1;
    % Extra processing for DC
    x_v_DC = zeros(salt.numReImEqns*numel(idxGenrou_SS_DC(f_DC)),1);
    x_v_DC(1:2:end) = x_v(idxGenrou_SS_DC(f_DC));
    % Get HB values from FD to TD
    genrou_x_v_DC_negDeltaT_0 = getTimeDomainSignal_iDFT(t_negDelta_0, ...
        @(~) 1:numel(x_v_DC),x_v_DC,f_DC,1) * 2; % x2 b/c DC
    genrou_x_v_W_negDeltaT_0 = getTimeDomainSignal_iDFT(t_negDelta_0, ...
        idxGenrou_SS_W,x_v,f,1) ;
    % Save TD values into EMT
    emt.x_v_prevTime(idxGenrou_TD) = [ ...
        genrou_x_v_DC_negDeltaT_0(:,1); ...
        genrou_x_v_W_negDeltaT_0(:,1) ...
        ];
    emt.x_v(idxGenrou_TD) = [ ...
        genrou_x_v_DC_negDeltaT_0(:,2); ...
        genrou_x_v_W_negDeltaT_0(:,2) ...
        ];
    % Process theta in emt because salt uses theta0 (i.e. does not
    % change w.r.t. time, does not include ramp)
    idxEmtSim_x_v_genTheta =  emt.getRowIdx_fromGenrouIndices(idxGen)-1 +...
        idxGenrouTD_Theta;
    emt.x_v_prevTime(idxEmtSim_x_v_genTheta) = mod( ...
        emt.x_v_prevTime(idxEmtSim_x_v_genTheta) + w*t_negDelta_0(1), ...
        2*pi);
    emt.x_v(idxEmtSim_x_v_genTheta) = mod( ...
        emt.x_v(idxEmtSim_x_v_genTheta) + w*t_negDelta_0(2), ...
        2*pi);
end
% Exciter
for idxExc = 1:salt.numExcDc1
    % Get indicies
    idxExc_SS_DC = @(~)salt.getRowIdx_fromExcDc1Indices(idxExc) + ...
        (1:salt.numExcDc1Eqns)-1;
    idxExc_TD = emt.getRowIdx_fromExcDc1Indices(idxExc) + ...
        (1:emt.numExcDc1Eqns)-1;
    % Extra processing for DC
    x_v_DC = zeros(salt.numReImEqns*numel(idxExc_SS_DC(f_DC)),1);
    x_v_DC(1:2:end) = x_v(idxExc_SS_DC(f_DC));
    % Get HB values from FD to TD
    excDc1_x_v_negDeltaT_0 = getTimeDomainSignal_iDFT(t_negDelta_0, ...
        @(~) 1:numel(x_v_DC),x_v_DC,f_DC,1)  * 2; % x2 bc DC
    % Save TD values into EMT
    emt.x_v_prevTime(idxExc_TD) = excDc1_x_v_negDeltaT_0(:,1);
    emt.x_v(idxExc_TD) = excDc1_x_v_negDeltaT_0(:,2);
end
% Gov
for idxGov = 1:salt.numTgov1d
    % Get indicies
    idxGov_SS_DC = @(~)salt.getRowIdx_fromTgov1dIndices(idxGov) + ...
        (1:salt.numTgov1dEqns)-1;
    idxGov_TD = emt.getRowIdx_fromTgov1dIndices(idxGov) + ...
        (1:emt.numTgov1dEqns)-1;
    % Extra processing for DC
    x_v_DC = zeros(salt.numReImEqns*numel(idxGov_SS_DC(f_DC)),1);
    x_v_DC(1:2:end) = x_v(idxGov_SS_DC(f_DC));
    % Get HB values from FD to TD
    tgov1d_x_v_negDeltaT_0 = getTimeDomainSignal_iDFT(t_negDelta_0, ...
        @(~) 1:numel(x_v_DC),x_v_DC,f_DC,1) * 2; % x2 b/c DC
    % Save TD values into EMT
    emt.x_v_prevTime(idxGov_TD) = tgov1d_x_v_negDeltaT_0(:,1);
    emt.x_v(idxGov_TD) = tgov1d_x_v_negDeltaT_0(:,2);
end
% Control values
idxGenRow = salt.getRowIdx_fromGenrouIndices(1:salt.numGenrou)-1;
emt.genrou_TorqueM = salt.x_v(idxGenRow+idxGenrou_Tm);
emt.genrou_TorqueM0 = salt.genrou_TorqueM0;
emt.genrou_efd = salt.x_v(idxGenRow+idxGenrou_Efd);
emt.genrou_efd0 = salt.genrou_efd0;
emt.tgov1d_Pref = salt.tgov1d_Pref;
emt.tgov1d_Pref0 = salt.tgov1d_Pref;
emt.excDc1_vref = salt.excDc1_vref;
emt.excDc1_vref0 = salt.excDc1_vref;
% Timer

% ---> DYNAMIC X_V (AT GRID FORMING IBR)
% GRID FORMING IBR
for idxIbrGF = 1:salt.numIbrGFM
    % Get indicies
    % (FD)
    idxIbrGFM_SS_DC = @(~) salt.getRowIdx_fromIbrGFMIndices(idxIbrGF) + ...
        [idxIbrGFM_Vg,idxIbrGFM_Vo,idxIbrGFM_If,idxIbrGFM_Io, ...
        idxIbrGFM_Vi,idxIbrGFM_Gamma,idxIbrGFM_IfRef,idxIbrGFM_X, ...
        idxIbrGFM_Wr,idxIbrGFM_VoRefDroop_q, ...
        idxIbrGFM_PqAvg,idxIbrGFM_Theta, ...
        idxIbrGFM_Vo_VR_avg,idxIbrGFM_Vo_VR,idxIbrGFM_VoRef] ...
        -1;
    idxIbrGFM_SS_W = @(~) salt.getRowIdx_fromIbrGFMIndices(idxIbrGF) + ...
        idxIbrGFM_IphABC ...
        -1;
    % (TD)
    idxIbrGFM_TD = emt.getRowIdx_fromIbrGFMIndices(idxIbrGF) + ...
        ... DC
        [idxIbrGFMTD_Vg,idxIbrGFMTD_Vo,idxIbrGFMTD_If,idxIbrGFMTD_Io, ...
        idxIbrGFMTD_Vi,idxIbrGFMTD_Gamma,idxIbrGFMTD_IfRef,idxIbrGFMTD_X, ...
        idxIbrGFMTD_Wr,idxIbrGFMTD_VoRefDroop_q, ...
        idxIbrGFMTD_PqAvg,idxIbrGFMTD_Theta, ...
        idxIbrGFMTD_Vo_VR_avg,idxIbrGFMTD_Vo_VR,idxIbrGFMTD_VoRef, ...
        ... W
        idxIbrGFMTD_Iabc] ...
        -1;
    % Extra processing for DC
    x_v_DC = zeros(salt.numReImEqns*numel(idxIbrGFM_SS_DC(f_DC)),1);
    x_v_DC(1:2:end) = x_v(idxIbrGFM_SS_DC(f_DC));
    % Get SS values from FD to TD
    ibrGFM_x_v_DC_negDeltaT_0 = getTimeDomainSignal_iDFT(t_negDelta_0, ...
        @(~) 1:numel(x_v_DC),x_v_DC,f_DC,1) * 2; % x2 b/c DC
    ibrGFM_x_v_W_negDeltaT_0 = getTimeDomainSignal_iDFT(t_negDelta_0, ...
        idxIbrGFM_SS_W,x_v,f,1);
    % Save TD values into EMT
    emt.x_v_prevTime(idxIbrGFM_TD) = [ ...
        ibrGFM_x_v_DC_negDeltaT_0(:,1); ...
        ibrGFM_x_v_W_negDeltaT_0(:,1) ...
        ];
    emt.x_v(idxIbrGFM_TD) = [ ...
        ibrGFM_x_v_DC_negDeltaT_0(:,2); ...
        ibrGFM_x_v_W_negDeltaT_0(:,2) ...
        ];
    % Process theta in emt because salt uess theta0 (i.e. does not
    % change w.r.t. time, does not include ramp)
    idxEmtSim_x_v_Theta =  emt.getRowIdx_fromIbrGFMIndices(idxIbrGF)-1 + ...
        idxIbrGFMTD_Theta;
    emt.x_v_prevTime(idxEmtSim_x_v_Theta) = mod( ...
        emt.x_v_prevTime(idxEmtSim_x_v_Theta) + ...
        w*t_negDelta_0(1), ...
        2*pi);
    emt.x_v(idxEmtSim_x_v_Theta) = mod( ...
        emt.x_v(idxEmtSim_x_v_Theta) + w*t_negDelta_0(2), ...
        2*pi);
end
% Control values
emt.ibrGFM_pset = salt.ibrGFM_pset;
emt.ibrGFM_qset = salt.ibrGFM_qset;
emt.ibrGFM_vo_q_set = salt.ibrGFM_voDroop_q_set;

% ---> DYNAMIC X_V (AT IM,ZIP)
% COMPOSITE LOADS
for idxLoadComp = 1:salt.numLoadComp
    % Get indicies
    % (FD)
    idxLoadComp_SS_DC = @(~) salt.getRowIdx_fromLoadCompIndices(idxLoadComp) + ...
        [idxLoadComp_Vs,idxLoadComp_WSlip,idxLoadComp_ThetaSys, ...
        idxLoadComp_Is,idxLoadComp_Ir,idxLoadComp_Wr, ...
        idxLoadComp_PQ,idxLoadComp_Vm,idxLoadComp_Vm,idxLoadComp_Izip] ...
        ... %          |____________________________|
        ... %              2x for filter in TD
        -1;
    idxLoadComp_SS_W = @(~) salt.getRowIdx_fromLoadCompIndices(idxLoadComp) + ...
        idxLoadComp_IphABC ...
        -1;
    % (TD)
    idxLoadComp_TD = emt.getRowIdx_fromLoadCompIndices(idxLoadComp) + ...
        ... DC
        [idxLoadCompTD_Vs,idxLoadCompTD_WSlip, ...
        idxLoadCompTD_ThetaSys,idxLoadCompTD_Is,idxLoadCompTD_Ir, ...
        idxLoadCompTD_Wr, ...
        idxLoadCompTD_PQ,idxLoadCompTD_VmPreFilt,idxLoadCompTD_Vm, ...
        idxLoadCompTD_Izip, ...
        ... W
        idxLoadCompTD_Iabc] ...
        -1;
    % Extra processing for DC
    x_v_DC = zeros(salt.numReImEqns*numel(idxLoadComp_SS_DC(f_DC)),1);
    x_v_DC(1:2:end) = x_v(idxLoadComp_SS_DC(f_DC));
    % Get SS values from FD to TD
    loadComp_x_v_DC_negDeltaT_0 = getTimeDomainSignal_iDFT(t_negDelta_0, ...
        @(~) 1:numel(x_v_DC),x_v_DC,f_DC,1) * 2; % x2 b/c DC
    loadComp_x_v_W_negDeltaT_0 = getTimeDomainSignal_iDFT(t_negDelta_0, ...
        idxLoadComp_SS_W,x_v,f,1);
    % Save TD values into EMT
    emt.x_v_prevTime(idxLoadComp_TD) = [ ...
        loadComp_x_v_DC_negDeltaT_0(:,1); ...
        loadComp_x_v_W_negDeltaT_0(:,1) ...
        ];
    emt.x_v(idxLoadComp_TD) = [ ...
        loadComp_x_v_DC_negDeltaT_0(:,2); ...
        loadComp_x_v_W_negDeltaT_0(:,2) ...
        ];
    % Process theta in emt because salt uses theta0 (i.e. does not
    % change w.r.t. time, does not include ramp)
    idxEmtSim_x_v_Theta = ...
        emt.getRowIdx_fromLoadCompIndices(idxLoadComp)-1 + ...
        idxLoadCompTD_ThetaSys;
    emt.x_v_prevTime(idxEmtSim_x_v_Theta) = mod( ...
        emt.x_v_prevTime(idxEmtSim_x_v_Theta) + ...
        w*t_negDelta_0(1) - eps, ...
        2*pi);
    emt.x_v(idxEmtSim_x_v_Theta) = mod( ...
        emt.x_v(idxEmtSim_x_v_Theta) + w*t_negDelta_0(2) - eps, ...
        2*pi);
end
% Control values
emt.loadCompIM_Tm0 = salt.loadCompIM_Tm0;
emt.loadCompZip_PQz = salt.loadCompZip_PQz;
emt.loadCompZip_PQi = salt.loadCompZip_PQi;
emt.loadCompZip_PQp = salt.loadCompZip_PQp;


% Frequency
idxW_Sim = emt.getRowIdx_wSys;
emt.x_v(idxW_Sim) = salt.x_v(idxW_SS);
emt.x_v_prevTime(idxW_Sim) = salt.x_v(idxW_SS);

% SAVE IN INITIALIZATION-SPECIFIC VARIABLE
emt.x_v0 = emt.x_v;
emt.x_v_prevTime0 = emt.x_v_prevTime;

%%
% --------------------------- HISTORY CURRENTS ----------------------------
% Include frequency coefficients at 60 Hz
% NOTE: Can ignore MNA variables because do not need to track current
% specifically for DC since no DC

% Solve FD current coefficients
rowIdx_Vabc = salt.getRowIdxAbc_fromBusNums(salt.bus);
bus_VComplex_3ph = complex(x_v(rowIdx_Vabc(1:2:end)),x_v(rowIdx_Vabc(2:2:end))) * ...
    exp(1j*w*-deltaT_TD); % Use prev time bc solving for I_prevTime
[tx_I_prevTime_complex_f,xfmr_I_prevTime_complex_f,load_I_prevTime_complex_f] = ....
    emt.historyCurrentInitializations(bus_VComplex_3ph,w);
% Add them as complex conjugates to accumulate real TD response
% NOTE: Don't need to multiply by 2 to accommodate complex conjugate
% symmetry.
emt.tx_I_prevTime = real(tx_I_prevTime_complex_f);
emt.xfmr_I_prevTime = real(xfmr_I_prevTime_complex_f);
emt.load_I_prevTime = real(load_I_prevTime_complex_f);

end