function [idxIabc,idxVg,idxVo,idxIf,idxIo,idxVi,idxGamma, ...
    idxIfRef,idxX,idxWr,idxVoRefDroop_q,idxPqAvg,idxTheta, ...
    idxVo_VR_avg,idxVo_VR,idxVoRef] = getIbrGFMIndicesTD
%GETIBRGFMINDICESTD  Accessor for the GFM IBR time-domain layout.
global idxIbrGFMTD_Iabc idxIbrGFMTD_Vg idxIbrGFMTD_Vo idxIbrGFMTD_If ...
       idxIbrGFMTD_Io idxIbrGFMTD_Vi idxIbrGFMTD_Gamma idxIbrGFMTD_IfRef ...
       idxIbrGFMTD_X idxIbrGFMTD_Wr idxIbrGFMTD_VoRefDroop_q ...
       idxIbrGFMTD_PqAvg idxIbrGFMTD_Theta idxIbrGFMTD_Vo_VR_avg ...
       idxIbrGFMTD_Vo_VR idxIbrGFMTD_VoRef %#ok<*GVMIS>
if isempty(idxIbrGFMTD_Iabc), emtInitIndices; end
idxIabc = idxIbrGFMTD_Iabc; idxVg = idxIbrGFMTD_Vg; idxVo = idxIbrGFMTD_Vo;
idxIf = idxIbrGFMTD_If; idxIo = idxIbrGFMTD_Io; idxVi = idxIbrGFMTD_Vi;
idxGamma = idxIbrGFMTD_Gamma; idxIfRef = idxIbrGFMTD_IfRef; idxX = idxIbrGFMTD_X;
idxWr = idxIbrGFMTD_Wr; idxVoRefDroop_q = idxIbrGFMTD_VoRefDroop_q;
idxPqAvg = idxIbrGFMTD_PqAvg; idxTheta = idxIbrGFMTD_Theta;
idxVo_VR_avg = idxIbrGFMTD_Vo_VR_avg; idxVo_VR = idxIbrGFMTD_Vo_VR;
idxVoRef = idxIbrGFMTD_VoRef;
end
